### ISSUE TITLE
Essential enhancements

### ISSUE THREAD

**Issue by Midnight1938** [manuvarkey/GElectrical#2]
Working in dark mode is very difficult, the colours don't contrast well.
![image](https://user-images.githubusercontent.com/58230351/228275707-ef17e48b-3e59-45bc-945f-affc2008ce78.png)

The ability to export selected part as png would be very appreciated

**Comment by manuvarkey** [comment]
Hi, @Midnight1938 

App has been updated to support dark themes. Please see screenshot. 

![Screenshot from 2023-03-31 09-04-34](https://user-images.githubusercontent.com/4415312/229022842-f9d1a2ab-6701-4c19-9350-35b875db48c7.png)

Flatpak version will be updated in a few hours.

**Comment by manuvarkey** [comment]
> The ability to export selected part as png would be very appreciated

Can you elaborate this point ? If it is to export a part of the drawing as png, that is already possible using any screenshot utility.

**Comment by Midnight1938** [comment]
> > The ability to export selected part as png would be very appreciated
> 
> Can you elaborate this point ? If it is to export a part of the drawing as png, that is already possible using any screenshot utility.

Yes, while its possible to do so with an SS utility, transparency is not retained
