### ISSUE TITLE
set  values 

### ISSUE THREAD

**Issue by javier-fer** [manuvarkey/GElectrical#3]
![captura](https://user-images.githubusercontent.com/20519707/232987074-2f2e4915-bc52-43df-bfc7-f258ba1898a3.png)

Hello Manu.
I'm testing electrical.
I cannot set the values of the elements, I get a forbidden signal.
Regards, thank you.

**Comment by manuvarkey** [comment]
@javier-fer  Try typing "Enter" after changing values.

**Comment by javier-fer** [comment]
thank you
