### ISSUE TITLE
i am facing an issue while running  python gelectrical_launcher.py could you help me

### ISSUE THREAD

**Issue by Adarsh-365** [manuvarkey/GElectrical#6]
I follow the steps you mentioned for Windows installation, still, I got the below error 
Traceback (most recent call last):
  File "gelectrical_launcher.py", line 27, in <module>
    import gi
  File "C:\Users\BATMAN1\AppData\Local\Programs\Python\Python38\lib\site-packages\gi\__init__.py", line 47, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified module could not be found. 

what should I do?

**Comment by manuvarkey** [comment]
@Adarsh01111 Are you using the windows installer located here [https://github.com/manuvarkey/GElectrical/releases/latest](https://github.com/manuvarkey/GElectrical/releases/latest) ?

**Comment by manuvarkey** [comment]
Source installation can be a bit tricky. Have you installed gvsbuild ?

**Comment by Adarsh01111** [comment]
> Source installation can be a bit tricky. Have you installed gvsbuild ?

yes I have install it gvsbuild using pipx install gvsbuild
![Screenshot (164)](https://github.com/manuvarkey/GElectrical/assets/102159256/387b2aea-7836-4a4a-8196-93d2000db0d4)

**Comment by manuvarkey** [comment]
This seems to be an issue with building pygobject. Can you try this suggestion from gvsbuild readme.

`If a build fails, try rebuilding it with --clean, if that fails, try rebuilding it with --from-scratch`

i.e. Try running.

`gvsbuild build --clean --enable-gi --py-wheel gtk3 pygobject adwaita-icon-theme`
or
`gvsbuild build --from-scratch --enable-gi --py-wheel gtk3 pygobject adwaita-icon-theme`

Also do not build gtk3 alone without the `--enable-gi` options.

**Comment by Adarsh01111** [comment]
i try gvsbuild build --from-scratch --enable-gi --py-wheel gtk3 pygobject adwaita-icon-theme
shows error


[problem2.txt](https://github.com/manuvarkey/GElectrical/files/12211972/problem2.txt)

**Comment by manuvarkey** [comment]
Seems like a gvsbuild issue. Let the upstream bug report be resolved.

https://github.com/wingtk/gvsbuild/issues/1020
