### ISSUE TITLE
Cannot move elements once placed

### ISSUE THREAD

**Issue by BenPalethorpe** [manuvarkey/GElectrical#7]
Hello.  I tried installing GElectrical on my RPi4 from Snap.  It looks great but I'm struggling with making a schematic easily.  Once I have placed an element (grid, busbar, load) on the sheet I cannot move it.  So once it is initially placed then it is stuck in that position forever.  I don't know if this is the expected behaviour, whether I'm doing something wrong or if it is an issue specific to the RPi4 installation?

Thanks for your help (and keep up the development!)
Ben

**Comment by manuvarkey** [comment]
You can use cut-paste for moving elements. Use Ctrl+x and Ctrl+v shortcuts.

**Comment by BenPalethorpe** [comment]
Apologies for taking so long to reply.  Thanks for your reply - using cut-paste works perfectly!  I can't believe I didn't think of that....

**Comment by BenPalethorpe** [comment]
Thanks - I'll try it out at the weekend!
